#配置说明参考 https://one.ms.netease.com/projects/gatewaz/wiki/%E6%96%B0%E5%B7%A5%E7%A8%8B_Getting_Started
spring:
  application:
    name: gzl-eureka #改成你的应用名
  profiles:
    active: test

server:
  port: 1111 #改成你的应用的端口，请到 https://git.ms.netease.com/huluwa/config-server 注册一个端口 @刘寅 @高振龙
  tomcat:
    access-log-enabled: true
    access-log-pattern: '%{X-Real-IP}i %l %u %t "%r" %s %b %D %T %{Referer}i "%{User-Agent}i" %I %v %a'
    basedir: ./
  #servlet-path: dispatchServlet

eureka:
  instance:
    hostname: gzl-eureka #改成你的应用名
    prefer-ip-address: true
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

#data:
#    elasticsearch:
#        cluster-name: kiwi-risk-application
#        cluster-nodes: 172.16.39.3:9300,172.16.39.4:9300,172.16.39.5:9300,172.16.39.6:9300,172.16.39.7:9300

endpoints:
  health:
    sensitive: false

management:
  context-path: /actuator
  security:
    enabled: false

demo:
  config:
    val: abc123-test

common:
  framework:
    application: pangu-risk

logging:
    config: classpath:logback-springboot.xml

## 测试环境制定服务提供地址
ribbon:
  eureka:
   enabled: false

pangu-task:
  ribbon:
    listOfServers: localhost:8001 #172.16.39.11:8001

mq:
    consumer:
      nameServer: 172.16.39.3:9876;172.16.39.4:9876
    producer:
      nameServer: 172.16.39.3:9876;172.16.39.4:9876
      group: blackWhiteListConsumer
      topicNum: 8